"use server";

import { readFile, writeFile } from "node:fs/promises";
import { extractAmplitudeVisemeTimeline } from "@/lib/audio-envelope-service";
import { synthesizeSpeech } from "@/lib/piper-service";
import { extractVisemeTimeline, type VisemeCue } from "@/lib/rhubarb-service";

// "amplitude" (default): subprocess-free, reads the WAV directly, mouth
// tracks loudness — near-instant, no Rhubarb dependency at all. "rhubarb":
// real recognizer-driven visemes, slower (even in Rhubarb's own fast
// "phonetic" mode) but not loudness-only. Set LIPSYNC_ENGINE=rhubarb to
// opt into it.
const LIPSYNC_ENGINE = process.env.LIPSYNC_ENGINE || "amplitude";

export interface NarrationResult {
  audioUrl?: string;
  visemeTimeline?: VisemeCue[];
  error?: string;
}

async function readCachedVisemes(
  cachePath: string,
): Promise<VisemeCue[] | null> {
  try {
    const raw = await readFile(cachePath, "utf-8");
    return JSON.parse(raw) as VisemeCue[];
  } catch {
    return null;
  }
}

/**
 * Synthesizes narration audio for a slide's script (Piper) and extracts its
 * viseme timeline for CourseNarrator's avatar — via a fast audio-amplitude
 * envelope by default, or Rhubarb if LIPSYNC_ENGINE=rhubarb. Both stages are
 * cached to disk keyed off the audio file Piper already hashes by
 * (voice, text) — a repeat call for the same slide script reuses both the
 * WAV and the viseme JSON instead of re-running either engine. The cache
 * filename includes the engine name so switching engines doesn't return a
 * stale timeline generated by the other one.
 */
export async function narrateSlideAction(
  scriptText: string,
): Promise<NarrationResult> {
  const trimmed = scriptText.trim();
  if (!trimmed) return { error: "empty_script" };

  const synth = await synthesizeSpeech(trimmed);
  if (synth.error || !synth.audioUrl || !synth.audioPath) {
    return { error: synth.error || "synthesis_failed" };
  }

  const visemeCachePath = `${synth.audioPath}.${LIPSYNC_ENGINE}.visemes.json`;
  const cached = await readCachedVisemes(visemeCachePath);
  if (cached) {
    return { audioUrl: synth.audioUrl, visemeTimeline: cached };
  }

  let timeline: VisemeCue[];
  if (LIPSYNC_ENGINE === "rhubarb") {
    const visemes = await extractVisemeTimeline(synth.audioPath, trimmed);
    // Rhubarb failing (e.g. binary unavailable) shouldn't block narration
    // audio — CourseNarrator falls back to a closed-mouth idle when
    // visemeTimeline is empty, so this degrades gracefully.
    timeline = visemes.timeline ?? [];
  } else {
    timeline = await extractAmplitudeVisemeTimeline(synth.audioPath);
  }

  if (timeline.length > 0) {
    await writeFile(visemeCachePath, JSON.stringify(timeline), "utf-8").catch(
      () => {},
    );
  }

  return { audioUrl: synth.audioUrl, visemeTimeline: timeline };
}

/**
 * Pre-synthesizes narration for every slide in a freshly generated course,
 * in parallel (same Promise.all pattern course-agent.ts already uses for
 * slide content itself). Fire this right after course generation instead
 * of waiting for the user to reach each slide — with the amplitude lipsync
 * path (~1.7s per slide, parallelizable), the whole course is ready in
 * roughly the time of its single slowest slide, not the sum of all of
 * them. Best-effort: a slide with an empty/failed script doesn't block the
 * others, and the caller doesn't need the results — narrateSlideAction's
 * own cache is what the course page actually reads from afterward.
 */
export async function pregenerateCourseNarrationAction(
  scripts: string[],
): Promise<{ succeeded: number; failed: number }> {
  const results = await Promise.all(
    scripts.map((script) => narrateSlideAction(script)),
  );
  const succeeded = results.filter((r) => r.audioUrl).length;
  return { succeeded, failed: results.length - succeeded };
}
